# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WonsinheungMid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WonsinheungMid
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WonsinheungMid
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftSoup'
  pod "CenteredCollectionView"
  pod 'lottie-ios'

  target 'WonsinheungMidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WonsinheungMidUITests' do
    # Pods for testing
  end


end